import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: "Ahmad's Portfolio" ,
  description: 'Generated by Ahmad',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
